# DigitalOcean App Platform – single-component fullstack (Dockerfile serves frontend + API)
# IMPORTANT: Fullstack container listens on 8080; spec must use http_port: 8080.
# After editing: paste this into App → Settings → App Spec → Edit, then Save.

name: lionfish-app
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

databases:
  - engine: PG
    name: dev-db-348203
    version: "17"

ingress:
  rules:
    - component:
        name: householdmanager
      match:
        path:
          prefix: /

services:
  - name: householdmanager
    github:
      repo: yamikuronue/HouseholdManager
      branch: main
      deploy_on_push: true

    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 8080

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, SECRET_KEY must be set under App-Level Environment Variables
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${dev-db-348203.DATABASE_URL}

      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        value: ${GOOGLE_CLIENT_ID}

      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ${GOOGLE_CLIENT_SECRET}

      # Add SECRET_KEY in the component's Environment Variables (dashboard) so it's not resolved from app-level
      - key: GOOGLE_REDIRECT_URI
        scope: RUN_TIME
        value: https://lionfish-app-uhfes.ondigitalocean.app/api/auth/callback

      - key: FRONTEND_URL
        scope: RUN_TIME
        value: https://lionfish-app-uhfes.ondigitalocean.app

      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
