# DigitalOcean App Platform Configuration
#
# Single component: backend + frontend built and served from one app (~$5/mo).
# Uses root Dockerfile (frontend + backend) to build and serve from one app.
#
# SETUP: 1) Update GitHub repo below  2) Set secrets in console (docs/ENV_VARIABLES.md)
#        3) After first deploy, set GOOGLE_REDIRECT_URI and FRONTEND_URL to your app URL

name: household-manager
region: nyc  # Change to your preferred region: nyc, sfo, ams, sgp, fra, tor, blr

services:
  # Single component: backend + frontend (root Dockerfile) — one app, ~$5/mo
  - name: web
    github:
      repo: your-username/HouseholdManager  # ⚠️ UPDATE THIS: your GitHub username/repo
      branch: main
      deploy_on_push: true
    
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
        value: ${GOOGLE_CLIENT_ID}
      
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SECRET_KEY}
      
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${DATABASE_URL}
      
      - key: GOOGLE_REDIRECT_URI
        scope: RUN_TIME
        value: https://lionfish-app-uhfes.ondigitalocean.app/api/auth/callback
      
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: https://lionfish-app-uhfes.ondigitalocean.app
      
      - key: API_HOST
        scope: RUN_TIME
        value: 0.0.0.0
      
      - key: API_PORT
        scope: RUN_TIME
        value: "8080"
      
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production

# ============================================
# Managed Database (Optional but Recommended)
# ============================================
# Uncomment the section below to use a managed PostgreSQL database
# The DATABASE_URL will be automatically set as an environment variable

databases:
  - name: household-manager-db
    engine: PG
    production: false  # Set to true for production
    version: "15"
    size_slug: db-s-dev-database  # Options: db-s-dev-database, db-s-1vcpu-1gb, db-s-1vcpu-2gb, etc.
    # The DATABASE_URL will be automatically injected as an environment variable
    # Format: postgresql://user:password@host:port/dbname?sslmode=require

# ============================================
# POST-DEPLOYMENT CHECKLIST
# ============================================
# After deploying, complete these steps:
#
# 1. App URL: https://lionfish-app-uhfes.ondigitalocean.app
#
# 2. Update Google Cloud Console:
#    - Go to https://console.cloud.google.com/apis/credentials
#    - Edit your OAuth 2.0 Client ID
#    - Add authorized redirect URI: https://lionfish-app-uhfes.ondigitalocean.app/api/auth/callback
#
# 3. Redeploy or update environment variables in console
# 4. Test: visit app URL, log in with Google, create household, add calendars
